import type { Metadata } from "next";
import { Mulish, Manrope } from "next/font/google";
import { ELang } from "@/models/Lang";
import "./globals.css";

const mulish = Mulish({ subsets: [ "cyrillic", "latin" ], weight: [ "300", "400", "700" ] });
const manrope = Manrope({ subsets: [ "latin" ], weight: [ "700" ] });

export const metadata: Metadata = {
    title: "Wish Hub",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang={ELang.UK}>
        <body className={ `${mulish.className} ${manrope.className}` }>{ children }</body>
        </html>
    );
}
