import type { Metadata } from "next";
import { Mulish, Manrope } from "next/font/google";
import "./globals.css";

const mulish = Mulish({ subsets: [ "cyrillic", "latin" ], weight: [ "300", "400", "700" ] });
const manrope = Manrope({ subsets: [ "latin" ], weight: [ "700" ] });

export const metadata: Metadata = {
    title: "Wish Hub",
    description: "Generated by create next app",
};

interface IProps {
    children: React.ReactNode;
    params: { locale: string; };

}

export default function RootLayout({ children, params: { locale } }: Readonly<IProps>) {
    return (
        <html lang={ locale }>
        <body className={ `${ mulish.className } ${ manrope.className }` }>{ children }</body>
        </html>
    );
}
